Sprint_2
vlvasi/qa_python pull request #2
Opened 2023-05-14 20:12 UTC by vlvasi

2023-05-15 18:39 UTC, kadirovgm requested changes

2023-05-15 18:39 UTC, kadirovgm commented on .idea/.gitignore
Нужно исправить: этот файл не имеет отношения к проекту, не стоит его пушить в основную ветку

2023-05-15 18:39 UTC, kadirovgm commented on .idea/inspectionProfiles/profiles_settings.xml
Нужно исправить: этот файл не имеет отношения к проекту, не стоит его пушить в основную ветку

2023-05-15 18:39 UTC, kadirovgm commented on .idea/misc.xml
Нужно исправить: этот файл не имеет отношения к проекту, не стоит его пушить в основную ветку

2023-05-15 18:39 UTC, kadirovgm commented on .idea/modules.xml
Нужно исправить: этот файл не имеет отношения к проекту, не стоит его пушить в основную ветку

2023-05-15 18:39 UTC, kadirovgm commented on .idea/qa_python.iml
Нужно исправить: этот файл не имеет отношения к проекту, не стоит его пушить в основную ветку

2023-05-15 18:39 UTC, kadirovgm commented on .idea/vcs.xml
Нужно исправить: этот файл не имеет отношения к проекту, не стоит его пушить в основную ветку

2023-05-15 18:39 UTC, kadirovgm commented on README.md
> +quote> 1. Проверка на то, что одна и та же книга не будет добалена дважны
Можно лучше: кажется стоит дописать список тестов :)

2023-05-15 18:39 UTC, kadirovgm commented on tests.py
> +        assert books_collector.get_books_with_specific_rating(6) == ["1984", "Animal Farm"]
Нужно исправить: один тест-одна проверка

2023-05-15 18:39 UTC, kadirovgm commented on tests.py
> +        books_collector.set_book_rating("The Great Gatsby", 8)
Нужно исправить: излишнее количество тестовых данных, хватит двух для проверки того, что книга находится по рейтингу

2023-05-15 18:39 UTC, kadirovgm commented on tests.py
> +    class TestBooksCollector:
Нужно исправить: не нужно для каждого метода писать класс, который к тому же повторяет другой по названию.

У нас все тестовые методы должны находиться внутри одного тестового класса, в данном случае этого достаточно, так как мы проверяем ограниченный блок функционала

2023-05-15 18:39 UTC, kadirovgm commented on tests.py
> +        books_collector.add_new_book("The Great Gatsby")
Нужно исправить: излишнее количество тестовых данных, хватит двух для проверки

2023-05-15 18:39 UTC, kadirovgm commented on tests.py
> +        assert books_collector.get_list_of_favorites_books() == ["The Great Gatsby"]
Нужно исправить: один тест-одна проверка

2023-05-15 18:39 UTC, kadirovgm commented on tests.py
> +        assert books_collector.get_list_of_favorites_books() == []
Нужно исправить: здесь стоит остановиться:)

2023-05-15 18:39 UTC, kadirovgm commented on tests.py
> +        books_collector.add_new_book("The Great Gatsby")
Нужно исправить: излишнее количество тестовых данных, хватит двух для проверки

2023-05-15 18:39 UTC, kadirovgm commented on tests.py
> +        books_collector.add_new_book("The Great Gatsby")
Нужно исправить: излишнее количество тестовых данных, хватит двух

2023-05-15 18:39 UTC, kadirovgm commented on tests.py
> +        assert books_collector.get_list_of_favorites_books() == ["The Great Gatsby", "1984"]
Можно лучше: также можно использовать конструкцию `in`

2023-05-18 13:27 UTC, vlvasi commented on .idea/misc.xml
Я не знаю, откуда взялись эти папки, у меня в pycharm их нет и удалить ничего не могу.
<img width="597" alt="Снимок экрана 2023-05-18 в 16 27 04" src="https://github.com/vlvasi/qa_python/assets/133156616/d5cc6705-77b7-4856-b9ac-fc54ca2f8fa4">

2023-05-18 13:28 UTC, vlvasi commented on .idea/misc.xml
<img width="1286" alt="Снимок экрана 2023-05-18 в 16 28 37" src="https://github.com/vlvasi/qa_python/assets/133156616/bb5e2dbd-2cca-4ed7-895b-350f2c819c6d">

2023-05-18 20:15 UTC, kadirovgm requested changes

2023-05-18 20:15 UTC, kadirovgm commented on tests.py
> +        assert books_collector.get_books_rating == {"The Great Gatsby": 1}
Отлично!

2023-05-18 20:15 UTC, kadirovgm commented on tests.py
>          assert books_collector.get_book_rating("The Great Gatsby") == 8
Отлично! одной проверки для юнит теста вполне достаточно

2023-05-18 20:15 UTC, kadirovgm commented on tests.py
>          assert books_collector.get_books_with_specific_rating(11) == []
Нужно исправить: странная проверка, лучше проверить позитивный кейс, что например по рейтингу 6 - две книги

2023-05-18 20:15 UTC, kadirovgm commented on tests.py
>          books_collector.add_new_book("1984")
Можно лучше: эта строка по сути лишняя

2023-05-18 20:15 UTC, kadirovgm commented on tests.py
>          assert books_collector.get_list_of_favorites_books() == ["The Great Gatsby"]
Можно лучше: можно воспользоваться `assert "The Great Gatsby" in books_collector.get_list_of_favorites_books()`

2023-05-18 20:15 UTC, kadirovgm commented on tests.py
>          books_collector.add_new_book("1984")
Можно лучше: эта строка лишняя, она не используется в тесте

2023-05-20 08:17 UTC, kadirovgm approved these changes

2023-05-30 20:26 UTC, merged